<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drop here</name>
   <tag></tag>
   <elementGuidId>3be8c974-0be5-457a-bae7-1f11036b334b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#droppable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='droppable']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#droppable</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8df037b1-f961-4699-af19-dfb157ce1bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>droppable</value>
      <webElementGuid>3f5ec596-94b7-4e26-8ee9-829560cc91c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-widget-header ui-droppable</value>
      <webElementGuid>16bdd933-b559-4999-9e1a-43bff04b2e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
						  Drop here
						</value>
      <webElementGuid>af3d05b3-62da-4389-a981-971d64875263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;droppable&quot;)</value>
      <webElementGuid>d21954e4-b884-4545-b7f7-1587c4dd0b0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='droppable']</value>
      <webElementGuid>94865e53-b533-47f9-9bfb-c63fc20d608a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-home']/div[2]</value>
      <webElementGuid>14267794-cc13-48f5-805f-f238783dd890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Revert Droppable'])[1]/following::div[4]</value>
      <webElementGuid>e8d124ee-287e-4f48-8147-ac911ba9ff8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prevent Propagation'])[1]/following::div[4]</value>
      <webElementGuid>cbb58e1e-fe6c-495e-b024-91bdb2946212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drop here'])[2]/preceding::div[1]</value>
      <webElementGuid>101b9d36-4046-4bc0-a530-3b38e9c47cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag me'])[1]/preceding::div[2]</value>
      <webElementGuid>303d6c59-72f1-4b26-9e74-9dfb9350764e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]</value>
      <webElementGuid>3025c252-2694-4249-86ac-a695b800a27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'droppable' and (text() = '
						  Drop here
						' or . = '
						  Drop here
						')]</value>
      <webElementGuid>5136ac15-eb95-4e0c-9154-e5b2ccf91664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
