<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asansol_sc-evWYkj dlvDax_1</name>
   <tag></tag>
   <elementGuidId>5b2df165-4337-4592-a7bb-6d0687b20676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='k']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.sc-evWYkj.dlvDax</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Asansol&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dea91fa3-c1d8-4922-b308-fb1059ea127a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Asansol</value>
      <webElementGuid>88328c6b-8458-441b-9efc-af845eddcb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-evWYkj dlvDax</value>
      <webElementGuid>7afb7b1b-5ca2-4abb-becd-5b7fbb5ac45c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>k</value>
      <webElementGuid>f6b59c67-4fb8-4422-af0d-d15c12f8a170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-gbzWSY aRiJE&quot;]/div[@class=&quot;sc-ellAub guqxhL&quot;]/div[@class=&quot;contents-wrapper&quot;]/div[@class=&quot;searchContainer&quot;]/div[@class=&quot;sc-kqlzXE geuHbm&quot;]/div[@class=&quot;sc-18n4g8v-0 gAhmYY sc-exdmVY hSrTai&quot;]/input[@class=&quot;sc-evWYkj dlvDax&quot;]</value>
      <webElementGuid>0b69eb69-28a8-4436-93fa-7ae452ddebce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='k']</value>
      <webElementGuid>039b231d-0180-45a8-9672-f1cdf6d487e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>e6eef85e-2e2d-4aad-b233-2ef3fbd33fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>59eb3635-f948-4c53-8060-770b9095d049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Asansol']</value>
      <webElementGuid>388d0c4e-35f7-4f14-aaeb-ad243d1f1373</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
