<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asansol_sc-evWYkj dlvDax_1_2</name>
   <tag></tag>
   <elementGuidId>444f3ed4-6232-43da-b2a7-589c5a463174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='ko']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.sc-evWYkj.dlvDax</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Asansol&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b32cb117-cbfc-4b4f-a7e8-2062fc5c1902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Asansol</value>
      <webElementGuid>b511759d-593b-460a-bc0b-330c90a1a97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-evWYkj dlvDax</value>
      <webElementGuid>a7055e46-870b-4f95-b42d-da9e6123faf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ko</value>
      <webElementGuid>364eae1e-a520-43cc-bc87-f63470924d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-gbzWSY aRiJE&quot;]/div[@class=&quot;sc-ellAub guqxhL&quot;]/div[@class=&quot;contents-wrapper&quot;]/div[@class=&quot;searchContainer&quot;]/div[@class=&quot;sc-kqlzXE geuHbm&quot;]/div[@class=&quot;sc-18n4g8v-0 gAhmYY sc-exdmVY hSrTai&quot;]/input[@class=&quot;sc-evWYkj dlvDax&quot;]</value>
      <webElementGuid>03fc884e-cae9-4e8d-a1ef-e7f86d9ad078</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='ko']</value>
      <webElementGuid>066ba886-6124-49e0-a2df-fc8f0e825984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>e841e5c4-d164-410f-9443-429308417c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d880240a-643d-408c-84a4-b6c6d92d2c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Asansol']</value>
      <webElementGuid>069c0c19-49f3-4741-b7bb-b5fdc69197ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
