<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asansol_sc-evWYkj dlvDax</name>
   <tag></tag>
   <elementGuidId>f23ce828-049d-4f99-810a-f1870fe3ed6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.sc-evWYkj.dlvDax</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Asansol&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d6a7566-94f4-48df-9647-0fa7933cf598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Asansol</value>
      <webElementGuid>495381d6-8655-4c4b-885c-6f6d500f14a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-evWYkj dlvDax</value>
      <webElementGuid>8ba17e92-e863-4df5-8942-b31568e05dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-gbzWSY aRiJE&quot;]/div[@class=&quot;sc-ellAub guqxhL&quot;]/div[@class=&quot;contents-wrapper&quot;]/div[@class=&quot;searchContainer&quot;]/div[@class=&quot;sc-kqlzXE geuHbm&quot;]/div[@class=&quot;sc-18n4g8v-0 gAhmYY sc-exdmVY hSrTai&quot;]/input[@class=&quot;sc-evWYkj dlvDax&quot;]</value>
      <webElementGuid>47a4f112-b0ca-4a6a-ac7a-c2e965a0d589</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>bfefa88c-536e-4743-ba57-7d65cf75639c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>0c66141e-5498-4050-925e-dcc83fe83a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ff9f8585-8d45-4c48-bc3d-0efb783dbb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Asansol']</value>
      <webElementGuid>beabe806-4a33-4d6b-8f3e-ff63c2d8d68a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
