<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Kolaghat</name>
   <tag></tag>
   <elementGuidId>284331b7-b9bf-4e93-8ac4-81dc9a989602</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div[2]/div/div/div/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Kolaghat&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c6adbf9e-3548-4c0e-a718-f0edb8e6d428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1hez2tp-0 sc-exdmVY lmxTfr</value>
      <webElementGuid>0d7e61ec-bba8-458e-8aa7-d945a7929edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kolaghat</value>
      <webElementGuid>7c9582fe-fc78-488d-83fc-178a73a24e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-gbzWSY aRiJE&quot;]/div[@class=&quot;sc-ellAub guqxhL&quot;]/div[@class=&quot;contents-wrapper&quot;]/div[@class=&quot;searchContainer&quot;]/div[@class=&quot;sc-kqlzXE geuHbm&quot;]/div[@class=&quot;sc-18n4g8v-0 gAhmYY sc-exdmVY hSrTai&quot;]/div[@class=&quot;sc-iKpIOp jnxihl&quot;]/div[@class=&quot;sc-ekHBYt sc-eTyWNx cvkNmY&quot;]/p[@class=&quot;sc-1hez2tp-0 sc-exdmVY lmxTfr&quot;]</value>
      <webElementGuid>4f2018c7-dfa2-4a3c-9c41-2d1eb7c70ac1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[2]/div/div/div/div[2]/p</value>
      <webElementGuid>7b737a83-ed63-46a9-9311-e4a0e07d8f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asansol'])[1]/following::p[3]</value>
      <webElementGuid>62cc9009-e628-49db-be31-e8107b655d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asansol'])[2]/preceding::p[28]</value>
      <webElementGuid>db666511-7833-4968-bb6d-e27b5c130581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asansol Locality'])[1]/preceding::p[29]</value>
      <webElementGuid>a8a607f2-ccee-4d1b-9415-87bfc004ac81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kolaghat']/parent::*</value>
      <webElementGuid>a4107554-90e8-4ec1-a598-a8f119eb7d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>64be2447-3c4b-4d67-8868-2255f7e98517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Kolaghat' or . = 'Kolaghat')]</value>
      <webElementGuid>9e4410bc-16d7-4b58-b558-42091acaca26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
