<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_down-triangle</name>
   <tag></tag>
   <elementGuidId>a2ae06fe-d75c-4915-ad9f-b48124ef301f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.sc-rbbb40-0.ezrcri</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;down-triangle&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>e3578c4e-f8df-4aa9-b035-f177c5fbb47f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>41d9f633-1cc7-45ed-bfe3-df613719e197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#4F4F4F</value>
      <webElementGuid>e13015c3-8771-49a4-ac71-dc3a16ce119c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>29ba42b6-0e70-45ec-86bc-700b25d0119f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>2d7f56c7-2e1d-44ee-9c41-84eda6a19dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 20 20</value>
      <webElementGuid>241b9564-7841-47aa-8ca3-b7c81b150742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>icon-svg-title- icon-svg-desc-</value>
      <webElementGuid>b8b6b4c8-43e3-4382-a7db-04c64fe5c109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a6b2d6b4-29d3-4af4-a3ef-ee372342d018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-rbbb40-0 ezrcri</value>
      <webElementGuid>6f618d22-85ce-4c20-adef-b38ad49fdb96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>down-triangle</value>
      <webElementGuid>fd8c94a2-d40c-40ba-94cc-c78b2b7663a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-gbzWSY aRiJE&quot;]/div[@class=&quot;sc-ellAub guqxhL&quot;]/div[@class=&quot;contents-wrapper&quot;]/div[@class=&quot;searchContainer&quot;]/div[@class=&quot;sc-kqlzXE geuHbm&quot;]/div[@class=&quot;sc-18n4g8v-0 gAhmYY sc-exdmVY hSrTai&quot;]/i[@class=&quot;sc-rbbb40-1 iFnyeo sc-kbGplQ gArJcv&quot;]/svg[@class=&quot;sc-rbbb40-0 ezrcri&quot;]</value>
      <webElementGuid>d95a0aac-e387-43b3-a45b-dda7ea59b798</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asansol'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>320e4259-6ff0-4123-a5e7-7c699aebe4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asansol'])[2]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>ba189edc-f551-46c8-bdec-fca2811cc875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asansol Locality'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>b9363742-814e-447b-ba86-91e0d4c53869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[(text() = 'down-triangle' or . = 'down-triangle')]</value>
      <webElementGuid>8b5a830e-08b9-421d-8128-a4ca00a91d64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
