<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Clear Inputs</name>
   <tag></tag>
   <elementGuidId>efbc7eca-2a91-4c8c-aec8-57a79ee6ed9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-clear-inputs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-clear-inputs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Clear Inputs&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07fbb75f-59e8-4ae2-bd92-2de7442381b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-clear-inputs</value>
      <webElementGuid>132b26a1-de55-40fa-9a49-15768eed3937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-danger ms-2</value>
      <webElementGuid>ebe85fc3-ca3b-4b26-b33c-314333bf3997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clear Inputs</value>
      <webElementGuid>bfc4ae71-c88c-441b-8cdf-5b7afc677cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-clear-inputs&quot;)</value>
      <webElementGuid>22083966-a75c-4f88-85e9-85ffedaeff58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-clear-inputs']</value>
      <webElementGuid>1bc2165e-00db-44dd-93f0-b89cbbf35512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display Inputs'])[1]/following::button[1]</value>
      <webElementGuid>ad906c7b-25f1-45ab-a58e-3a92a163891a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web inputs page for Automation Testing Practice'])[2]/following::button[2]</value>
      <webElementGuid>0a34628b-e43a-494f-a7d6-911c546e79b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input: Number'])[1]/preceding::button[1]</value>
      <webElementGuid>4332cb9e-1da4-4206-9ef7-5113b29c7184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input: Text'])[1]/preceding::button[1]</value>
      <webElementGuid>9207117e-a54c-4f8a-9d34-2397599b0064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clear Inputs']/parent::*</value>
      <webElementGuid>1570adf7-1e38-4f77-a417-948bc23ba6b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>82d777bc-c22f-4311-a3df-7ee0cfcc08f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-clear-inputs' and (text() = 'Clear Inputs' or . = 'Clear Inputs')]</value>
      <webElementGuid>d0d5b7cb-f0aa-4826-bc1c-3cbcf304f8fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
