<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Display Inputs</name>
   <tag></tag>
   <elementGuidId>fd918071-ce1f-447b-a71a-6658bd209358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-display-inputs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-display-inputs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Display Inputs&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1380b208-4212-4634-a342-c5447ced097b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-display-inputs</value>
      <webElementGuid>121ca968-7fe4-46da-908f-5c3b56da9f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-primary</value>
      <webElementGuid>303c1a8d-6301-4035-955f-3fa9dbb2377d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Display Inputs</value>
      <webElementGuid>a5b015f8-70a3-4744-bd0b-56ccb30e779f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-display-inputs&quot;)</value>
      <webElementGuid>d5c16d23-53dd-407a-aa42-717d0bf36ce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-display-inputs']</value>
      <webElementGuid>7bf4b47e-047e-4186-a6e9-6916ec00a943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web inputs page for Automation Testing Practice'])[2]/following::button[1]</value>
      <webElementGuid>4d60b2b7-9b2b-4c8c-b903-0820a9b89f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inputs'])[1]/following::button[1]</value>
      <webElementGuid>fe9c8827-4908-4920-8963-396b53a019b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Inputs'])[1]/preceding::button[1]</value>
      <webElementGuid>a23b6ed8-869e-4cdc-a0d0-837597f49425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input: Number'])[1]/preceding::button[2]</value>
      <webElementGuid>3126016e-d507-41d5-96ba-2e3fc80c9883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Display Inputs']/parent::*</value>
      <webElementGuid>9b7b2856-ab58-420f-acfa-e08a42c35570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>82a7d8ee-78ed-488d-bc4b-6cd85b8b3bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-display-inputs' and (text() = 'Display Inputs' or . = 'Display Inputs')]</value>
      <webElementGuid>af38670d-4245-422a-8cb0-dcbf5ed5ce7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
