<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email-ID is not valid_telephoneno</name>
   <tag></tag>
   <elementGuidId>963b8a6c-8a75-4669-a602-cd8222f1c2f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#telephoneno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='telephoneno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Mobile Number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f058fc2-4464-4c46-bac8-04412473e281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>58c211b3-621f-487b-94c9-c205e9d51aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>telephoneno</value>
      <webElementGuid>5523f506-5610-4803-ae0a-4c2bdac829f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telephoneno</value>
      <webElementGuid>130c9a3e-9b9c-4957-ac31-2fd2d1498849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>425dcab3-5d42-4df6-a5e7-2dcc2ba1843a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile Number</value>
      <webElementGuid>b1488207-ab34-443c-b8d9-90557bd77090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validateTelephone();</value>
      <webElementGuid>3375203b-9802-43d4-ba5c-4a01427e2fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validateTelephone();</value>
      <webElementGuid>280101b1-c01a-4b94-bb19-79f0392a1b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telephoneno&quot;)</value>
      <webElementGuid>14887825-faa9-4b2f-b350-1eac35828332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='telephoneno']</value>
      <webElementGuid>b88f10ba-a0c6-4e09-970c-b178f8c4c262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div/form/div/div[8]/input</value>
      <webElementGuid>0f90a67d-cddb-4864-8d05-331506f3e045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>f78501b7-a01c-43cd-b765-b4fe4fb0537c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'telephoneno' and @id = 'telephoneno' and @placeholder = 'Mobile Number']</value>
      <webElementGuid>b1fc6300-3e8c-4733-8f90-aaf4c7e5e213</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
