<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Billing address_fname</name>
   <tag></tag>
   <elementGuidId>1ddf4b40-7bd8-497b-ae79-5fa0247e62b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;FirstName&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>851b96c2-ab10-464a-9ab9-a7e81be6362e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb33925a-9aa1-49cb-aea7-fcf1e6540dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fname</value>
      <webElementGuid>c9844a55-fff6-42ce-8ab6-7c1bb3d93c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fname</value>
      <webElementGuid>863f25f1-7743-4d1f-bc6c-c0e313146382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>FirstName</value>
      <webElementGuid>243312e7-f7da-4678-bd72-0aed2d65f85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validatecustomername();</value>
      <webElementGuid>31273adb-4dc4-4b93-a0b1-010656e844b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validatecustomername();</value>
      <webElementGuid>40988023-d7c1-4125-a654-8c7394fc7fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fname&quot;)</value>
      <webElementGuid>6082a3be-9da7-4ffc-91e3-799bd9267b8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fname']</value>
      <webElementGuid>c5eb63f8-144e-44f1-9fe6-c97d65f909c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div/form/div/div[4]/input</value>
      <webElementGuid>83cfdd0c-51ce-4ed2-953e-229606baaf31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>65d19f08-b411-4f07-ae4c-8631a30e5049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fname' and @id = 'fname' and @placeholder = 'FirstName']</value>
      <webElementGuid>07e2e7d5-e637-4250-91be-93a06cbfdc0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
