<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Course</name>
   <tag></tag>
   <elementGuidId>d2fa2fa4-c10e-4904-9560-367c7ec76890</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@name='courses']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=group[name=&quot;Web Table Example&quot;i] >> #product</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//table[@name='courses']</value>
      <webElementGuid>f534b790-3e8d-49fc-bf36-d4da8beb5590</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
