<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email</name>
   <tag></tag>
   <elementGuidId>475b50f7-69c0-455c-9b58-44fab0963d5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_user_detail_attributes_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_user_detail_attributes_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;youremail@abv.bg&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3727428-2383-4a70-9ed8-47d74eaf7550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_user_detail_attributes_email</value>
      <webElementGuid>15cde7dc-d28e-4686-a3bb-cdf834e72402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>youremail@abv.bg</value>
      <webElementGuid>03ff3e2e-85bd-45c0-89b5-d40ae380344d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>62528d5a-4bef-4c35-bb83-797af31d1005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>35df26ef-3c5a-46ea-911e-3cb2643147e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_user_detail_attributes_email&quot;)</value>
      <webElementGuid>eee2ba7e-f067-4b3e-a294-aa25b555b30c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_user_detail_attributes_email']</value>
      <webElementGuid>c37ad195-320f-4f95-bc61-1a4629a1c5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_user']/div[5]/div/input</value>
      <webElementGuid>027dd902-73b8-4207-b288-a27688d39e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>6a6962e2-a3f5-4c99-a34b-2077259faf3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_user_detail_attributes_email' and @placeholder = 'youremail@abv.bg' and @name = 'email' and @type = 'email']</value>
      <webElementGuid>b05daa51-6784-4963-8e85-fc7c796a9381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
