<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full_licencetype</name>
   <tag></tag>
   <elementGuidId>84125980-164a-43b1-9fbd-0518b9f3bf04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#licencetype_f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='licencetype_f']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Provisional&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85f6ad6b-816d-4d24-bca1-e7ecd14ceda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>licencetype_f</value>
      <webElementGuid>a33fa0ee-bd39-4eb9-9c7f-70911bb94fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>licencetype</value>
      <webElementGuid>9034da18-e917-43c3-82bb-aaaeaf70ca6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Provisional</value>
      <webElementGuid>e7a83dc7-2861-4d41-9190-7cb74f085796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>983e9bd0-d738-4823-b8a5-e17b024895e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;licencetype_f&quot;)</value>
      <webElementGuid>5de4f9b5-9a81-4abd-9700-6ac478cb8f62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='licencetype_f']</value>
      <webElementGuid>84968513-3807-4752-8522-db4941231f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_user']/div[2]/div[4]/input[2]</value>
      <webElementGuid>ad82784c-9bea-48b8-a458-46bf515b934c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>07146be6-7d04-4933-8d7a-7531c55ba246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'licencetype_f' and @name = 'licencetype' and @type = 'radio']</value>
      <webElementGuid>452f4c48-1f19-4e58-afd2-e073db21a082</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
