<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Post code_post_code</name>
   <tag></tag>
   <elementGuidId>c11527ed-39a2-4b28-84f0-871de84a2e43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_address_attributes_postcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_address_attributes_postcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;sy24 5be&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c57346d4-8925-4c3e-b634-191a111120f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_address_attributes_postcode</value>
      <webElementGuid>d157e2c0-3d26-4fdf-98aa-f64a74b82ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>sy24 5be</value>
      <webElementGuid>a13f196d-b851-4a2d-bb0c-d19c64a7167d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>post_code</value>
      <webElementGuid>ac3cf109-ebb0-49cb-9557-ce5a4bf7100b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae4378f4-64da-46fd-b7f4-fd2fd1e93640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_address_attributes_postcode&quot;)</value>
      <webElementGuid>b96984f2-ee6e-4cb3-acf6-6bce7747e68e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_address_attributes_postcode']</value>
      <webElementGuid>c5ef005c-7389-49e1-a858-239206d531b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_user']/div[4]/div[4]/input</value>
      <webElementGuid>5309df4f-ad9e-4c3e-81f7-6818cae120e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/input</value>
      <webElementGuid>ba1457b4-ccb9-4d2c-8391-2d9e96ccb8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_address_attributes_postcode' and @placeholder = 'sy24 5be' and @name = 'post_code' and @type = 'text']</value>
      <webElementGuid>cb7ca4ab-4db8-4c50-8402-0fff112f7176</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
