<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_County_county</name>
   <tag></tag>
   <elementGuidId>f1d879b2-5585-443e-b29c-7f746cf348d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_address_attributes_county</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_address_attributes_county']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;County&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c25c8827-3e97-4826-aaf5-6e72a32f187e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_address_attributes_county</value>
      <webElementGuid>6808003d-3ca4-407d-a115-7605b2267f90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>county</value>
      <webElementGuid>70ec4f4f-1479-4b00-8e11-861d699cd0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4e4dde2-5fa8-4ed6-9558-d4b4488bf2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_address_attributes_county&quot;)</value>
      <webElementGuid>06fab357-f939-491c-95b6-2074b7136313</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_address_attributes_county']</value>
      <webElementGuid>72cb2467-7830-40f0-bd69-5b83432cb1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_user']/div[4]/div[3]/input</value>
      <webElementGuid>e251fe63-0a98-4fb9-9b9b-2d1a293f51b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>52ea4aef-b545-4db1-9077-63031930a5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_address_attributes_county' and @name = 'county' and @type = 'text']</value>
      <webElementGuid>94535041-8ee7-41a5-b108-0261e3ede1db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
