<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname_lastname</name>
   <tag></tag>
   <elementGuidId>1a0e0987-46d9-496b-af8e-4f9bc2035970</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_surname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_surname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Surname&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eee8a99a-666e-42e0-b068-eae39a46486f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_surname</value>
      <webElementGuid>3e64e03c-815d-4133-bed4-185927e6f788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastname</value>
      <webElementGuid>b29263be-cae1-4066-afbc-d227182c7342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>633cf521-86b0-46e7-850e-f34363dce4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_surname&quot;)</value>
      <webElementGuid>9a10fa61-d13b-435f-8dba-51f3568cdea4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_surname']</value>
      <webElementGuid>52b6f2f1-1d03-49ac-9b8f-fc0e6f090968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_user']/div[2]/div/input</value>
      <webElementGuid>4d0e735e-0623-4cb1-9314-ef6dfc0053fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>fefd8ab1-1d73-4a29-90ef-55cdf3efd732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_surname' and @name = 'lastname' and @type = 'text']</value>
      <webElementGuid>19bd3d03-ad84-4a1b-acaf-2e7629ec4154</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
