<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password</name>
   <tag></tag>
   <elementGuidId>bcc0fb74-fddc-40f4-8cf4-861b112170dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_user_detail_attributes_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_user_detail_attributes_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Password&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2be73f86-330e-4af4-bbc5-39253a70149d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_user_detail_attributes_password</value>
      <webElementGuid>20eec966-cc06-4ca9-9cf2-07d9d089d2a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>affb1640-deff-43ce-90ec-25bdefb50dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>19d79f86-bfe8-4fa8-8d4b-95bf02cd04b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_user_detail_attributes_password&quot;)</value>
      <webElementGuid>9f833fd7-a48f-4724-8376-328b6f10f243</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_user_detail_attributes_password']</value>
      <webElementGuid>831a2d65-248a-4aa5-a02c-3d573f16f476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_user']/div[5]/div[2]/input</value>
      <webElementGuid>38d4c8af-6cbb-4878-8a48-ad08fa4ad11d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>558af98e-e975-4f81-8e19-fbee3254cd75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_user_detail_attributes_password' and @name = 'password' and @type = 'password']</value>
      <webElementGuid>068a06b7-6910-4ccc-85bb-aee1ad2fed49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
