<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_licencetype</name>
   <tag></tag>
   <elementGuidId>6c01184f-36cb-42b2-bdc3-4d16c12d2743</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#licencetype_t</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='licencetype_t']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Full&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d45a8922-4032-4084-b217-50bdb6fe9273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>00aec48a-dda8-4a51-96e0-e819fe3a6b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>licencetype_t</value>
      <webElementGuid>958da65e-1636-470d-babb-3c1c59862c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>licencetype</value>
      <webElementGuid>12a64967-d5cf-4a66-bff7-d3ce4c3bdcba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Full</value>
      <webElementGuid>1849759a-9963-4421-b8f0-47723d65bb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7b866142-2cc8-4199-83df-eb16a8e64bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;licencetype_t&quot;)</value>
      <webElementGuid>36b9235c-f9cd-4367-a6ed-31a01790b94e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='licencetype_t']</value>
      <webElementGuid>3a785609-c83f-4b53-92f5-e38f352d57e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_user']/div[2]/div[4]/input</value>
      <webElementGuid>0a8a9ed3-dd6c-43f9-a0ef-07b26c6d5250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>f437acae-4656-4166-8368-28f4889ec021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@checked = 'checked' and @id = 'licencetype_t' and @name = 'licencetype' and @type = 'radio']</value>
      <webElementGuid>e0b26d0a-1c7e-4d43-89dc-819262f62a23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
