<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm password_c_password</name>
   <tag></tag>
   <elementGuidId>e132a75e-369b-4984-97b8-751b7f372286</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_user_detail_attributes_password_confirmation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user_user_detail_attributes_password_confirmation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#user_user_detail_attributes_password_confirmation</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4348b0c0-b75f-421c-b71d-5e551ec5e712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user_user_detail_attributes_password_confirmation</value>
      <webElementGuid>bb00bad5-3921-49d8-8861-77d930720a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c_password</value>
      <webElementGuid>4247e6bd-2442-4b6f-9b8b-73cb4b05ce20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>113ea62c-95c4-4936-b633-d74f972d8b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_user_detail_attributes_password_confirmation&quot;)</value>
      <webElementGuid>b64493eb-9a17-45ed-938e-8cc5716396c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user_user_detail_attributes_password_confirmation']</value>
      <webElementGuid>94a29fa4-7792-4ea9-aeed-cdcbcd6ea4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_user']/div[5]/div[3]/input</value>
      <webElementGuid>96c9adc6-9d9b-431d-856b-f48fe0f5c099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/input</value>
      <webElementGuid>8b5a208b-baa4-4d83-b810-19f393e5ccb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'user_user_detail_attributes_password_confirmation' and @name = 'c_password' and @type = 'password']</value>
      <webElementGuid>31ea6b06-77f4-4227-bf61-291872a5c528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
